
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-final-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-final-project
  template:
    metadata:
      labels:
        app: devops-final-project
    spec:
      containers:
      - image: mayamitova/devops-final-project
        name: devops-final-project
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: devops-final-project-config
data:
  application.yml: |-
    spring:
     cloud:
      kubernetes:
        discovery:
          all-namespaces: false
          service-labels:
            spring-boot: true
---

apiVersion: v1
kind: Service
metadata:
  name: devops-final-project
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "devops-final-project"
    port: 8080
  selector:
    app: devops-final-project
