apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-final-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-final-project
  template:
    metadata:
      labels:
        app: devops-final-project
    spec:
      containers:
        - image: diyanfilipov/devops-final-project:telerik
          name: devops-final-project

---

apiVersion: v1
kind: Service
metadata:
  name: devops-final-project
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "devops-final-project"
      port: 10333
  selector:
    app: devops-final-project