# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ test ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate-gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
  SAST:
    needs: validate-gradle
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Jacoco Report
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        run: ./gradlew sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
  # This workflow contains a single job called "build"
  build:
    needs: [validate-gradle, SAST]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      run: ./gradlew build

#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew

#     - name: Test coverage with Gradle
#       run: >
#         ./gradlew testCoverage
