# file: .github/workflows/preview.yaml
on:
  push:
#    types: [ closed ]
    branches:
      - test
jobs:
  deploy_app_job:
    # this job will only run if the PR has been merged
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo PR #${{ github.event.number }} has been merged
      - uses: actions/checkout@v2
      - name: Build project
        run: ./gradlew build
      - name: Build a Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:${{ env.IMAGE_TAG }} . \

          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:${{ env.IMAGE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:latest
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish docker image
        #if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project
      - name: Context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
#       - name: Build
#         uses: okteto/actions/build@v1
#         with:
#           token: ${{ secrets.OKTETO_TOKEN }}
#           tag: ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:${{ github.sha }}
      - name: Get Kubeconfig
        uses: okteto/actions/namespace@v1
        id: kubeconf-step
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: ${{ secrets.OKTETO_NAMESPACE }}
      - name: Deploy and Wait
        uses: okteto/actions/deploy@v1
#        env:
#          KUBECONFIG: ${{ steps.kubeconf-step.outputs.kubeconfig }}
        with:
          namespace: ${{ secrets.OKTETO_NAMESPACE }}
          manifest: k8s.yml
          tag: ${{ secrets.DOCKERHUB_USERNAME }}/devops-final-project:${{ github.sha }}
          waitOn: deployment/devops-final-project
      - name: Sleep for 90 seconds
        run: sleep 90s
        shell: bash
      - name: Verify
        uses: srt32/uptime@master
        with:
          url-to-hit: https://devops-final-project-${{ secrets.OKTETO_NAMESPACE }}.cloud.okteto.net/course/1
          expected-statuses: "200"
  slack_notification:
    name: Slack Notification
      runs-on: ubuntu-latest
      steps:
        - name: Slack Notification
          uses: slackapi/slack-github-action@v1.17.0
          with:
            # For posting a rich message using Block Kit
            payload: |
              {
                "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    }
                  }
                ]
              }
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

#      - name: Deploy preview environment
#        uses: okteto/deploy-preview@latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          name: pr-${{ github.event.number }}-mayamitova
#          timeout: 15m
