# file: .github/workflows/preview.yaml
on:
  pull_request:
    types: [ closed ]
    branches:
      - test
jobs:
  deploy_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
          echo PR #${{ github.event.number }} has been merged
    - name: Context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Deploy preview environment
      uses: okteto/deploy-preview@latest
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: pr-${{ github.event.number }}-mayamitova
        timeout: 15m
